# Generated by Django 5.1.2 on 2024-12-15 03:17

from django.db import migrations

from django.db import migrations

def add_authors(apps, schema_editor):
    Author = apps.get_model('app1', 'Author')

    authors = [
        "J.K. Rowling",
        "George Orwell",
        "J.R.R. Tolkien",
        "Harper Lee",
        "Mark Twain",
        "Jane Austen",
        "Charles Dickens",
        "F. Scott Fitzgerald",
        "Ernest Hemingway",
        "Leo Tolstoy"
    ]

    for name in authors:
        Author.objects.create(name=name)

class Migration(migrations.Migration):
    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_authors),
    ]

